version: '3'
services:

  jaeger:
    image: jaegertracing/all-in-one:1.14
    container_name: jaeger
    ports:
      - 5778:5778
      - 9411:9411
      - 14250:14250
      - 14268:14268
      - 16686:16686
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    depends_on:
      - jaeger
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 13133:13133
      - 4317:4317
      - 55680:55680

